(define-color-theme "gruvbox-material" ()
  (:display-background-mode :dark)
  (:foreground "#a89984")
  (:background "#292828")
  (:inactive-window-background nil)
  (region :foreground nil :background "#005f00")
  (modeline :bold t :foreground "#8a8a8a" :background "#121212")
  (modeline-inactive :bold t :foreground "#6c6c6c" :background "#121212")
  (syntax-warning-attribute :foreground "#ffff00")
  (syntax-string-attribute :foreground "#945e80")
  (syntax-comment-attribute :foreground "#928374")
  (syntax-keyword-attribute :foreground "#ea6962")
  (syntax-constant-attribute :foreground "#00d75f")
  (syntax-function-name-attribute :foreground "#89b482")
  (syntax-variable-attribute :foreground "#87ff00")
  (syntax-type-attribute :foreground "#7daea3")
  (syntax-builtin-attribute :bold t :foreground "#a9b665"))

(define-color-theme "gruvbox-material-light" ()
  (:display-background-mode :light)
  (:foreground "#292828")
  (:background "#a89984")
  (:inactive-window-background nil)
  (region :foreground nil :background "#005f00")
  (modeline :bold t :foreground "#8a8a8a" :background "#121212")
  (modeline-inactive :bold t :foreground "#6c6c6c" :background "#121212")
  (syntax-warning-attribute :foreground "#ffff00")
  (syntax-string-attribute :foreground "#945e80")
  (syntax-comment-attribute :foreground "#928374")
  (syntax-keyword-attribute :foreground "#ea6962")
  (syntax-constant-attribute :foreground "#6c782e")
  (syntax-function-name-attribute :foreground "#4c7a5d")
  (syntax-variable-attribute :foreground "#87ff00")
  (syntax-type-attribute :foreground "#45707a")
  (syntax-builtin-attribute :bold t :foreground "#b47109"))


(define-color-theme "svelte-high-contrast" ()
  (:display-background-mode :dark)
  (:foreground "#c8d3f5")
  (:background "#000000")
  (:inactive-window-background nil)
  (region :foreground nil :background "#005f00")
  (modeline :bold t :foreground "#8a8a8a" :background "#121212")
  (modeline-inactive :bold t :foreground "#6c6c6c" :background "#121212")
  (syntax-warning-attribute :foreground "#ffff00")
  (syntax-string-attribute :foreground "#00d75f")
  (syntax-comment-attribute :foreground "#636da6")
  (syntax-keyword-attribute :foreground "#c73c3f")
  (syntax-constant-attribute :foreground "#00d75f")
  (syntax-function-name-attribute :foreground "#89b482")
  (syntax-variable-attribute :foreground "#87ff00")
  (syntax-type-attribute :foreground "#7daea3")
  (syntax-builtin-attribute :bold t :foreground "#a9b665"))

(define-color-theme "svelte" ()
  (:display-background-mode :dark)
  (:foreground "#c8d3f5")
  (:background "#0e070d")
  (:inactive-window-background nil)
  (region :foreground nil :background "#005f00")
  (modeline :bold t :foreground "#8a8a8a" :background "#121212")
  (modeline-inactive :bold t :foreground "#6c6c6c" :background "#121212")
  (syntax-warning-attribute :foreground "#ffff00")
  (syntax-string-attribute :foreground "#00d75f")
  (syntax-comment-attribute :foreground "#636da6")
  (syntax-keyword-attribute :foreground "#c73c3f")
  (syntax-constant-attribute :foreground "#00d75f")
  (syntax-function-name-attribute :foreground "#89b482")
  (syntax-variable-attribute :foreground "#87ff00")
  (syntax-type-attribute :foreground "#7daea3")
  (syntax-builtin-attribute :bold t :foreground "#a9b665"))

(load-theme "gruvbox-material") 
